import { useState } from "react";
import { Alert, Image, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { getLanguageCode, getNativeLanguageName, translate } from "../../constants/translations";

const API_URL = "http://10.20.56.14:5000";
type Product = { _id?: string; title?: string; description?: string; category?: string; craft?: string; images?: string[]; materials?: { name?: string }[]; pricing?: { suggestedPrice?: number; currency?: string }; originalLanguage?: string; translations?: { language?: string; title?: string; description?: string }[]; artisan?: { name?: string; location?: string } };
const text = (item: unknown) => typeof item === "string" ? item.trim() : "";

export default function ArtisanProductDetails() {
  const params = useLocalSearchParams<{ product?: string; language?: string }>();
  const selectedLanguage = getLanguageCode(params.language);
  const [product, setProduct] = useState<Product>(() => { try { return params.product ? JSON.parse(params.product) : {}; } catch { return {}; } });
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [galleryVisible, setGalleryVisible] = useState(false);
  const availableTranslations = product.translations?.filter((item) => text(item.title) || text(item.description)) || [];
  const [translationLanguage, setTranslationLanguage] = useState<string>(selectedLanguage);
  const selectedTranslation = availableTranslations.find((item) => getLanguageCode(item.language) === getLanguageCode(translationLanguage));
  const displayedTitle = text(selectedTranslation?.title) || text(product.title);
  const displayedDescription = text(selectedTranslation?.description) || text(product.description);
  const [priceDraft, setPriceDraft] = useState(() => typeof product.pricing?.suggestedPrice === "number" ? String(product.pricing.suggestedPrice) : "");
  const image = Array.isArray(product.images) ? text(product.images[0]) : "";
  const images = Array.isArray(product.images) ? product.images.map(text).filter(Boolean) : [];
  const update = (field: "title" | "description" | "category", value: string) => setProduct((current) => ({ ...current, [field]: value }));

  const saveChanges = async () => {
    if (!product._id) return;
    const parsedPrice = priceDraft.trim() ? Number(priceDraft) : undefined;
    if (priceDraft.trim() && (!Number.isFinite(parsedPrice ?? NaN) || (parsedPrice ?? 0) < 0)) { Alert.alert(translate(selectedLanguage, "invalidPrice"), translate(selectedLanguage, "enterValidPriceShort")); return; }
    try { setSaving(true); const response = await fetch(`${API_URL}/api/catalog/${product._id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: product.title, description: product.description, category: product.category, pricing: { ...product.pricing, suggestedPrice: parsedPrice } }) }); if (!response.ok) throw new Error(); setProduct((current) => ({ ...current, pricing: { ...current.pricing, suggestedPrice: parsedPrice } })); setEditing(false); Alert.alert(translate(selectedLanguage, "saved"), translate(selectedLanguage, "productUpdated")); }
    catch { Alert.alert(translate(selectedLanguage, "saveFailedTitle"), translate(selectedLanguage, "couldNotSaveProduct")); }
    finally { setSaving(false); }
  };
  const deleteProduct = () => Alert.alert(translate(selectedLanguage, "deleteConfirm"), translate(selectedLanguage, "deleteConfirm"), [{ text: translate(selectedLanguage, "cancel"), style: "cancel" }, { text: translate(selectedLanguage, "delete"), style: "destructive", onPress: async () => { if (!product._id) return; try { const response = await fetch(`${API_URL}/api/catalog/${product._id}`, { method: "DELETE" }); if (!response.ok) throw new Error(); router.back(); } catch { Alert.alert(translate(selectedLanguage, "saveFailedTitle"), translate(selectedLanguage, "couldNotSaveProduct")); } } }]);

  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ {translate(selectedLanguage, "back")}</Text></Pressable>{image ? <Pressable onPress={() => setGalleryVisible(true)} accessibilityLabel={translate(selectedLanguage, "viewPhotos")}><Image source={{ uri: image }} style={styles.image} /></Pressable> : <View style={styles.placeholder}><Text style={styles.placeholderText}>SIH</Text></View>}
    {editing ? <TextInput value={text(product.title)} onChangeText={(value) => update("title", value)} style={styles.input} /> : <Text style={styles.title}>{displayedTitle || translate(selectedLanguage, "product")}</Text>}
    {editing ? <TextInput value={text(product.category)} onChangeText={(value) => update("category", value)} style={styles.input} /> : <Text style={styles.category}>{text(product.category) || translate(selectedLanguage, "handcrafted")}</Text>}
    {editing ? <TextInput keyboardType="decimal-pad" value={priceDraft} onChangeText={setPriceDraft} placeholder={translate(selectedLanguage, "priceNotAvailable")} placeholderTextColor="#8A8A84" style={styles.input} /> : <Text style={styles.price}>{typeof product.pricing?.suggestedPrice === "number" ? `${text(product.pricing.currency) || "INR"} ${product.pricing.suggestedPrice}` : translate(selectedLanguage, "priceNotAvailable")}</Text>}
    <View style={styles.section}><Text style={styles.sectionTitle}>{translate(selectedLanguage, "description")}</Text>{editing ? <TextInput multiline value={text(product.description)} onChangeText={(value) => update("description", value)} style={[styles.input, styles.multiline]} /> : <><View style={styles.languageTabs}>{availableTranslations.map((item) => { const isActive = getLanguageCode(item.language) === getLanguageCode(translationLanguage); return <Pressable key={item.language} onPress={() => setTranslationLanguage(item.language || selectedLanguage)} style={[styles.languageTab, isActive && styles.languageTabActive]}><Text style={[styles.languageTabText, isActive && styles.languageTabTextActive]}>{getNativeLanguageName(item.language)}</Text></Pressable>; })}</View><Text style={styles.body}>{displayedDescription || translate(selectedLanguage, "description")}</Text></>}</View>
    <Info label={translate(selectedLanguage, "materials")} value={product.materials?.map((item) => text(item.name)).filter(Boolean).join(", ") || ""} /><Info label={translate(selectedLanguage, "craft")} value={text(product.craft)} /><Info label={translate(selectedLanguage, "originalLanguage")} value={text(product.originalLanguage)} /><Info label={translate(selectedLanguage, "artisanLabel")} value={[text(product.artisan?.name), text(product.artisan?.location)].filter(Boolean).join(" | ")} />
    <View style={styles.actions}>{editing ? <Pressable onPress={saveChanges} disabled={saving} style={styles.primary}><Text style={styles.primaryText}>{saving ? "..." : translate(selectedLanguage, "save")}</Text></Pressable> : <Pressable onPress={() => setEditing(true)} style={styles.primary}><Text style={styles.primaryText}>{translate(selectedLanguage, "edit")}</Text></Pressable>}<Pressable onPress={deleteProduct} style={styles.delete}><Text style={styles.deleteText}>{translate(selectedLanguage, "delete")}</Text></Pressable></View>
  </ScrollView><Modal visible={galleryVisible} animationType="slide" onRequestClose={() => setGalleryVisible(false)}><SafeAreaView style={styles.galleryScreen}><View style={styles.galleryHeader}><Text style={styles.galleryTitle}>{translate(selectedLanguage, "viewPhotos")}</Text><Pressable onPress={() => setGalleryVisible(false)}><Text style={styles.closeText}>{translate(selectedLanguage, "close")}</Text></Pressable></View><ScrollView contentContainerStyle={styles.galleryList}>{images.map((uri, index) => <Image key={`${uri}-${index}`} source={{ uri }} style={styles.galleryImage} />)}</ScrollView></SafeAreaView></Modal></SafeAreaView>;
}
function Info({ label, value }: { label: string; value: string }) { return value ? <View style={styles.section}><Text style={styles.sectionTitle}>{label}</Text><Text style={styles.body}>{value}</Text></View> : null; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#F7F5EF" }, content: { padding: 20, paddingBottom: 45 }, back: { color: "#087F5B", fontSize: 17, fontWeight: "700", paddingVertical: 8 }, image: { backgroundColor: "#E7ECE5", borderRadius: 16, height: 270, marginTop: 10, width: "100%" }, placeholder: { alignItems: "center", backgroundColor: "#DDEBE2", borderRadius: 16, height: 270, justifyContent: "center", marginTop: 10, width: "100%" }, placeholderText: { color: "#087F5B", fontSize: 40, fontWeight: "800" }, title: { color: "#173B35", fontSize: 29, fontWeight: "800", marginTop: 20 }, category: { color: "#087F5B", fontSize: 16, fontWeight: "600", marginTop: 6 }, price: { color: "#B6532C", fontSize: 19, fontWeight: "700", marginTop: 12 }, section: { borderTopColor: "#D8DED8", borderTopWidth: 1, marginTop: 22, paddingTop: 15 }, sectionTitle: { color: "#173B35", fontSize: 17, fontWeight: "700" }, languageTabs: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 12 }, languageTab: { borderColor: "#D8DED8", borderRadius: 8, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 7 }, languageTabActive: { backgroundColor: "#087F5B", borderColor: "#087F5B" }, languageTabText: { color: "#59655F", fontSize: 13, fontWeight: "600" }, languageTabTextActive: { color: "#FFFFFF" }, body: { color: "#59655F", fontSize: 16, lineHeight: 24, marginTop: 6 }, input: { backgroundColor: "#FFF", borderColor: "#D8DED8", borderRadius: 10, borderWidth: 1, color: "#173B35", fontSize: 18, marginTop: 14, padding: 12 }, multiline: { minHeight: 100, textAlignVertical: "top" }, actions: { flexDirection: "row", gap: 12, marginTop: 30 }, primary: { alignItems: "center", backgroundColor: "#087F5B", borderRadius: 10, flex: 1, padding: 14 }, primaryText: { color: "#FFF", fontWeight: "700" }, delete: { alignItems: "center", borderColor: "#B33A2B", borderRadius: 10, borderWidth: 1, flex: 1, padding: 14 }, deleteText: { color: "#B33A2B", fontWeight: "700" }, galleryScreen: { backgroundColor: "#F7F5EF", flex: 1 }, galleryHeader: { alignItems: "center", borderBottomColor: "#D8DED8", borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: 20 }, galleryTitle: { color: "#173B35", fontSize: 20, fontWeight: "800" }, closeText: { color: "#087F5B", fontSize: 16, fontWeight: "700" }, galleryList: { gap: 16, padding: 20 }, galleryImage: { backgroundColor: "#E7ECE5", borderRadius: 12, height: 300, width: "100%" } });